# Generated by Django 5.0.3 on 2024-04-02 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_employees_project_employess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='employess',
            new_name='employees',
        ),
    ]
